{% set name = "hdc-algo" %}
{% set data = load_setup_py_data() %}
{% set version = os.environ.get("VERSION", "") or data.get("version").replace("-dev", ".dev") %}
{% set build = os.environ.get("BUILD", "0") %}

source:
  path: ../../

package:
  name: {{ name|lower }}-core
  version: {{ version }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build }}

requirements:
  build:
    - pip
  host:
    - python
  run:
    - python >=3.7
    - xarray
    - dask-core
    - numba

test:
  imports:
    - hdc.algo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WFP-VAM/hdc-algo/
  summary: xarray tools for seasonal monitor
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - valpesendorfer
    - Kirill888
