{% set name = "hdc-algo" %}
{% set version = os.environ.get("VERSION", "0.1.2") %}
{% set build = os.environ.get("BUILD", "0") %}

source:
  url: https://data.earthobservation.vam.wfp.org/pypi/{{ name }}/{{ name }}-{{ version }}.tar.gz


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build }}

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - xarray
    - dask-core
    - numba

test:
  imports:
    - hdc.algo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WFP-VAM/hdc-algo/
  summary: xarray tools for seasonal monitor
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - valpesendorfer
    - Kirill888
