name: Publish to S3
on:
  workflow_run:
    workflows: ["Run Code Checks"]
    branches:
      - main
    types:
      - completed

jobs:
  publish-s3:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: wheels_cache
        with:
          path: ./wheels
          key: wheels-${{ github.sha }}

      - uses: actions/cache@v3
        id: pkgs_cache
        with:
          path: pkgs
          key: pkgs-${{ github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_S3_UPLOAD_ROLE }}
          aws-region: eu-central-1

      - name: upload wheels to S3
        run: |
          aws s3 sync wheels/ ${S3_DEST}/

          # re-render index.html
          aws s3 ls ${S3_DEST}/ | ./scripts/render-simple-index.awk > wheels/index.html
          # need to copy it as index.html into "directory"
          aws s3 cp wheels/index.html ${S3_DEST}/index.html
          # but also as a file with the same name as directory,
          # so that `curl http://${host}/pypi/seasmon-xr` works
          aws s3 cp wheels/index.html ${S3_DEST} --content-type text/html

        env:
          S3_DEST: s3://wfp-share/pypi/seasmon-xr

      - name: upload conda packages to S3
        run: |
          aws s3 sync pkgs/ ${S3_DEST}/noarch/

        env:
          S3_DEST: s3://wfp-share/hdc