name: Run Code Checks
on:
  push:
  pull_request:

jobs:
  env38:
    uses: WFP-VAM/seasmon_xr/.github/workflows/pyenv.yaml@main
    with:
      python-version: "3.8"
      run: |
          echo $LD_LIBRARY_PATH
          echo "$PATH"
          which python
          python --version

  black:
    needs: [env38]
    uses: WFP-VAM/seasmon_xr/.github/workflows/pyenv.yaml@main
    with:
      python-version: "3.8"
      run: black --check .

  pylint:
    needs: [env38]
    uses: WFP-VAM/seasmon_xr/.github/workflows/pyenv.yaml@main
    with:
      python-version: "3.8"
      run: pylint seasmon_xr

  pydocstyle:
    needs: [env38]
    uses: WFP-VAM/seasmon_xr/.github/workflows/pyenv.yaml@main
    with:
      python-version: "3.8"
      run: pydocstyle seasmon_xr

  mypy:
    needs: [env38]
    uses: WFP-VAM/seasmon_xr/.github/workflows/pyenv.yaml@main
    with:
      python-version: "3.8"
      run: mypy seasmon_xr

  wheels:
    runs-on: ubuntu-20.04
    needs:
      - env38
      - black
    steps:
      - uses: actions/checkout@v2
      - name: Get Python Env from Cache
        uses: actions/cache@v2
        with:
          key: ${{ needs.env38.outputs.cache-key }}
          path: ${{ needs.env38.outputs.cache-path }}

      - name: Update PATH
        shell: bash
        run: |
          echo "${py_path}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${py_path}/lib" >> $GITHUB_ENV
        env:
          py_path: ${{ needs.env38.outputs.cache-path }}

      - uses: actions/cache@v2
        id: wheels_cache
        with:
          path: ./wheels
          key: wheels-${{ github.sha }}

      - name: build wheels unpatched
        run: |
          mkdir wheels
          pip wheel \
            --verbose \
            --no-input \
            --no-deps \
            --exists-action w \
            --wheel-dir wheels \
          .

          python setup.py sdist -d wheels

      - name: patch version
        run: |
          python ./scripts/patch_version.py ${GITHUB_RUN_NUMBER:-0} ./seasmon_xr/_version.py

      - name: build wheels patched version
        if: matrix.python-version == 3.8
        run: |
          pip wheel \
            --verbose \
            --no-input \
            --no-deps \
            --exists-action w \
            --wheel-dir wheels \
          .

          python setup.py sdist -d wheels

      - name: Upload results (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheels
          if-no-files-found: error

  tests:
    runs-on: ubuntu-20.04
    needs:
      - env38
      - black
    steps:
      - uses: actions/checkout@v2
      - name: Get Python Env from Cache
        uses: actions/cache@v2
        with:
          key: ${{ needs.env38.outputs.cache-key }}
          path: ${{ needs.env38.outputs.cache-path }}

      - name: Update PATH
        shell: bash
        run: |
          echo "${py_path}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${py_path}/lib" >> $GITHUB_ENV
        env:
          py_path: ${{ needs.env38.outputs.cache-path }}

      - name: Run test with coverage
        run: |
          python -m pytest -s \
            --cov \
            --cov-report=term \
            tests/

  finished:
    runs-on: ubuntu-20.04
    needs:
      - wheels
      - tests
      - black
      - pylint
      - mypy
      - pydocstyle
    steps:
      - uses: actions/checkout@v2
