name: Run Code Checks
on:
  push:
  pull_request:

jobs:
  pyenv:
    uses: WFP-VAM/seasmon_xr/.github/workflows/pyenv.yaml@main
    with:
      python-version: "3.8"
      run: |
          echo $LD_LIBRARY_PATH
          echo "$PATH"
          which python
          python --version

  black:
    needs:
      - pyenv
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Python Env from Cache
        uses: actions/cache@v2
        with:
          key: ${{ needs.pyenv.outputs.cache-key }}
          path: ${{ needs.pyenv.outputs.cache-path }}
      - name: Update PATH
        run: |
          echo "${py_path}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${py_path}/lib" >> $GITHUB_ENV
        env:
          py_path: ${{ needs.pyenv.outputs.cache-path }}

      - name: run black
        run: black --check .

  linting:
    needs:
      - pyenv
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Python Env from Cache
        uses: actions/cache@v2
        with:
          key: ${{ needs.pyenv.outputs.cache-key }}
          path: ${{ needs.pyenv.outputs.cache-path }}
      - name: Update PATH
        run: |
          echo "${py_path}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${py_path}/lib" >> $GITHUB_ENV
        env:
          py_path: ${{ needs.pyenv.outputs.cache-path }}

      - name: pylint
        run: pylint seasmon_xr
      - name: pydocstyle
        run:  pydocstyle seasmon_xr
      - name: mypy
        run: mypy seasmon_xr

  wheels:
    needs:
      - pyenv
      - black
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Python Env from Cache
        uses: actions/cache@v2
        with:
          key: ${{ needs.pyenv.outputs.cache-key }}
          path: ${{ needs.pyenv.outputs.cache-path }}
      - name: Update PATH
        shell: bash
        run: |
          echo "${py_path}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${py_path}/lib" >> $GITHUB_ENV
        env:
          py_path: ${{ needs.pyenv.outputs.cache-path }}

      - uses: actions/cache@v2
        id: wheels_cache
        with:
          path: ./wheels
          key: wheels-${{ github.sha }}

      - name: build wheels unpatched
        run: |
          mkdir -p wheels
          pip wheel \
            --verbose \
            --no-input \
            --no-deps \
            --exists-action w \
            --wheel-dir wheels \
          .

          python setup.py sdist -d wheels

      - name: patch version
        run: |
          python ./scripts/patch_version.py ${GITHUB_RUN_NUMBER:-0} ./seasmon_xr/_version.py

      - name: build wheels patched version
        run: |
          pip wheel \
            --verbose \
            --no-input \
            --no-deps \
            --exists-action w \
            --wheel-dir wheels \
          .

          python setup.py sdist -d wheels

      - name: Upload results (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheels
          if-no-files-found: error

  tests:
    needs:
      - pyenv
      - black
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Python Env from Cache
        uses: actions/cache@v2
        with:
          key: ${{ needs.pyenv.outputs.cache-key }}
          path: ${{ needs.pyenv.outputs.cache-path }}
      - name: Update PATH
        shell: bash
        run: |
          echo "${py_path}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${py_path}/lib" >> $GITHUB_ENV
        env:
          py_path: ${{ needs.pyenv.outputs.cache-path }}

      - name: Run test with coverage
        run: |
          python -m pytest -s \
            --cov \
            --cov-report=term \
            tests/

  test-wheel:
    needs:
      - pyenv
      - black
      - wheels
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Python Env from Cache
        uses: actions/cache@v2
        with:
          key: ${{ needs.pyenv.outputs.cache-key }}
          path: ${{ needs.pyenv.outputs.cache-path }}
      - name: Update PATH
        shell: bash
        run: |
          echo "${py_path}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${py_path}/lib" >> $GITHUB_ENV
        env:
          py_path: ${{ needs.pyenv.outputs.cache-path }}

      - name: Get Wheels
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheels

      - name: Install dev wheel
        run: |
          find wheels/ -type f -name "*.dev*.whl" | head -1 | xargs python -m pip install

      - name: Test Code from the wheel
        run: |
          cd tests/
          python -m pytest -s .
